### ISSUE TITLE
Method not allowed / Payload too large errors

### ISSUE THREAD

**Issue by Yiddishe-Kop** [laravel/reverb#218]
### Reverb Version

1.0.0-beta14

### Laravel Version

11.13.0

### PHP Version

8.3.3

### Description

Deployed Reverb via Forge to production, and I get the following error:
```
[2024-06-29 21:25:36] production.ERROR: Pusher error: Method not allowed.. {"userId":1,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: Method not allowed.. at /home/forge/.../vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:164)
[stacktrace]
#0 /home/forge/.../vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
#1 /home/forge/.../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle()
#2 /home/forge/.../vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /home/forge/.../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
```
Locally this error doesn't happen.

Another error I do get locally:
```
[2024-06-29 21:49:41] local.ERROR: Pusher error: Payload too large.. {"userId":11,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: Payload too large.. at .../vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:164)
[stacktrace]
#0 .../vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Object(Illuminate\\Support\\Collection), 'App\\\\Events\\\\Host...', Array)
#1 .../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle(Object(Illuminate\\Broadcasting\\BroadcastManager))
```

### Steps To Reproduce

My Event class:
```
namespace App\Events;

use App\Models\Event;
use App\Data\EventStatData;
use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcastNow;

class EventStatsUpdated implements ShouldBroadcastNow
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(
        public Event $event
        ) {
    }

    public function broadcastWith(): array
    {
        return EventStatData::from($this->event->stats)->toArray();
    }

    public function broadcastOn(): array
    {
        return [
            new Channel("Events.{$this->event->id}.stats"),
        ];
    }
}
```
Usage:
```
broadcast(new EventStatsUpdated($this));
```
local `.env`:
```
REVERB_APP_ID=812456
REVERB_APP_KEY=1cd7uv8gp2fv6y1tlxyi
REVERB_APP_SECRET=pacnwjlkxjgfkeums21o
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```
production .env
```
REVERB_APP_ID=396379
REVERB_APP_KEY=h95uycobejaarqfzftpq
REVERB_APP_SECRET=3lpzwncd1yvflc5pnubm
REVERB_HOST=ws.my.app # my domain
REVERB_PORT=443
REVERB_SCHEME="https"

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

**Comment by jonhassall** [comment]
Have you tried increasing the size of 'max_message_size' in config/reverb.php ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Qraxin** [comment]
@Yiddishe-Kop hello! I had the same error `Pusher error: Method not allowed..`. In my situation, the reason was a discrepancy in settings:
I had
```env
REVERB_PORT=80
REVERB_SCHEME="http"
```

But it should be:
```env
REVERB_PORT=443
REVERB_SCHEME="https"
```
The Forge re-recorded my initial settings.

**Comment by MohammedAbdelkarem** [comment]
> Have you tried increasing the size of 'max_message_size' in config/reverb.php ?

that works fine for me, i have tried to max the max_request_size and it fails to solve the error, but the max_message_size works fine, thanks
