### ISSUE TITLE
'Pusher Error: ' on broadcasting any event which implements ShouldBroadcast or ShouldBroadcastNow

### ISSUE THREAD

**Issue by muhammadZihad** [laravel/reverb#279]
### Reverb Version

1.4.3

### Laravel Version

11.34.2

### PHP Version

8.3

### Description

I have recently upgraded our laravel application from laravel 9 to laravel 11 and php 8.2 to 8.3. 
I am running Laravel Reverb on my local apache server. When my reverb server is running,  I am getting the following error when broadcasting any event:
```
broadcast(new PropertySubmissionBroadcastEvent($this, $event));
```

This is the stacktrace:

```
Pusher error: . {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: . at C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster.php:164)
[stacktrace]
#0 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Object(Illuminate\\Support\\Collection), 'Modules\\\\Propert...', Array)
#1 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle(Object(Illuminate\\Broadcasting\\BroadcastManager))
#2 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(126): Illuminate\\Container\\Container->call(Array)
#7 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#8 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#9 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(130): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastManager.php(182): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#11 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(357): Illuminate\\Broadcasting\\BroadcastManager->queue(Object(Modules\\Property\\Events\\PropertySubmissionBroadcastEvent))
#12 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(280): Illuminate\\Events\\Dispatcher->broadcastEvent(Object(Modules\\Property\\Events\\PropertySubmissionBroadcastEvent))
#13 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('Modules\\\\Propert...', Array, false)
#14 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\PendingBroadcast.php(72): Illuminate\\Events\\Dispatcher->dispatch('Modules\\\\Propert...')
#15 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(223): Illuminate\\Broadcasting\\PendingBroadcast->__destruct()
#16 C:\\wamp64\\www\\real-estate\\Modules\\Property\\Models\\Property.php(2339): broadcast(Object(Modules\\Property\\Events\\PropertySubmissionBroadcastEvent))
#17 C:\\wamp64\\www\\real-estate\\app\\Services\\NotificationManagers\\PushNotificationManager.php(36): Modules\\Property\\Models\\Property->broadcastPushNotification(Object(Modules\\Notification\\Enums\\NotificationEventTypeEnum), 'test', 'abc')
#18 C:\\wamp64\\www\\real-estate\\app\\Factories\\NotificationFactory.php(101): App\\Services\\NotificationManagers\\PushNotificationManager->dispatch()
#19 C:\\wamp64\\www\\real-estate\\Modules\\Property\\Jobs\\HandlePropertySubmission.php(45): App\\Factories\\NotificationFactory->dispatch()
#20 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Modules\\Property\\Jobs\\HandlePropertySubmission->handle()
#21 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#23 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(694): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(126): Illuminate\\Container\\Container->call(Array)
#26 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Modules\\Property\\Jobs\\HandlePropertySubmission))
#27 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Modules\\Property\\Jobs\\HandlePropertySubmission))
#28 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(130): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(78): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Modules\\Property\\Jobs\\HandlePropertySubmission))
#30 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bus\\PendingDispatch.php(205): Illuminate\\Bus\\Dispatcher->dispatch(Object(Modules\\Property\\Jobs\\HandlePropertySubmission))
#31 C:\\wamp64\\www\\real-estate\\app\\Services\\NotificationDispatcherService.php(35): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#32 C:\\wamp64\\www\\real-estate\\routes\\web.php(30): App\\Services\\NotificationDispatcherService::dispatch(Object(Modules\\Notification\\Enums\\NotificationEventTypeEnum), Object(Modules\\Property\\Models\\Property))
#33 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\CallableDispatcher.php(40): Illuminate\\Routing\\RouteFileRegistrar->{closure}()
#34 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(243): Illuminate\\Routing\\CallableDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Closure))
#35 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(214): Illuminate\\Routing\\Route->runCallable()
#36 C:\\wamp64\\www\\real-estate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(808): Illuminate\\Routing\\Route->run()
```

### Steps To Reproduce

run `php artisan reverb:start --debug`
```
broadcast(new PropertySubmissionBroadcastEvent($this, $event));
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by muhammadZihad** [comment]
Thank you for responding @crynobone . Here is the repo link: https://github.com/muhammadZihad/reverb_event_dispatch_issue

I have added a route `/` in web.php which will broadcast the event and will die and dump the exception.

**Comment by muhammadZihad** [comment]
Found the issue. When I broadcast an event, it sends a post request to the following url : `REVERB_HOST:REVERB_POST/apps/REVERB_APP_ID/events`

The problem is, I had a frontend project running on port `8080` and Reverb was using the same port `8080`. This was causing the error. Because, while making the post request, it was hitting the frontend project url and getting 404 all the time.

Sorry for the trouble.
